### ISSUE TITLE
 Preferred Data Format for Training New Model

### ISSUE THREAD

**Issue by Fumin66** [zademn/PU-GCN-pytorch#3]
Hello,

When training a new model myself, what data format should I prepare and into which folder should I place it?

Thank you.

**Comment by zademn** [comment]
Your own data will have its own format. I took the format that was given in PU1K (which was hdf5). 
You should write your own pyg Dataset class that outputs `PairData` (the one I defined [here](https://github.com/zademn/PU-GCN-pytorch/blob/master/utils/data.py)) and you can use them as in the training notebook "train" function.

**Comment by Fumin66** [comment]
Thank you for your response.

I would also like to format my data in the same way as PU1K. I have point cloud data in the xyz format. Do you know how I can format this data to match the PU1K format?

**Comment by zademn** [comment]
You mean hdf5? You can use h5py for that.

**Comment by Fumin66** [comment]
Thank you for your response.

I referred to [this](https://github.com/BingHan0458/PU-GACNet/blob/master/data_preprocessing/prep_data/generateH5.py) to convert the dataset format from a pcd file.
I've resolved it.
